#pragma once

#include <Arduino.h>

struct RobotState {
  float rawAx = 0.0f;
  float rawAy = 0.0f;
  float rawAz = 0.0f;
  float rawGx = 0.0f;
  float rawGy = 0.0f;
  float rawGz = 0.0f;
  float correctedGx = 0.0f;
  float correctedGy = 0.0f;
  float correctedGz = 0.0f;
  float imuRawAxG = 0.0f;
  float imuRawAyG = 0.0f;
  float imuRawAzG = 0.0f;
  float imuRawAccelNormG = 0.0f;
  float imuRawGxDps = 0.0f;
  float imuRawGyDps = 0.0f;
  float imuRawGzDps = 0.0f;
  float imuRawMx = 0.0f;
  float imuRawMy = 0.0f;
  float imuRawMz = 0.0f;
  float imuRawMagDirectionDeg = 0.0f;
  float imuCorrectedAxG = 0.0f;
  float imuCorrectedAyG = 0.0f;
  float imuCorrectedAzG = 0.0f;
  float imuCorrectedGxDps = 0.0f;
  float imuCorrectedGyDps = 0.0f;
  float imuCorrectedGzDps = 0.0f;
  float imuCorrectedMxUt = 0.0f;
  float imuCorrectedMyUt = 0.0f;
  float imuCorrectedMzUt = 0.0f;
  float imuMagNormUt = 0.0f;
  float imuAccelRollDeg = 0.0f;
  float imuAccelPitchDeg = 0.0f;
  float imuFilteredRollDeg = 0.0f;
  float imuFilteredPitchDeg = 0.0f;
  float imuRelativeRollDeg = 0.0f;
  float imuRelativePitchDeg = 0.0f;
  float imuHeadingDeg = 0.0f;
  float imuFilterAlpha = 0.0f;
  float imuAccelOffset[3] = {};
  float imuAccelScale[3] = {1.0f, 1.0f, 1.0f};
  float imuGyroOffset[3] = {};
  float imuMagOffset[3] = {};
  float imuMagScale[3] = {1.0f, 1.0f, 1.0f};
  float imuVerticalRollDeg = 0.0f;
  float imuVerticalPitchDeg = 0.0f;
  uint16_t imuRawSampleRateHz = 0;
  uint16_t imuAccelRateHz = 0;
  uint16_t imuGyroRateHz = 0;
  uint16_t imuMagRateHz = 0;
  uint32_t imuCalibrationSamples = 0;
  unsigned long imuSampleAgeMs = 0;
  uint8_t imuRawAddress = 0;
  uint8_t imuRawId = 0;
  uint8_t imuRawMagId = 0;
  bool imuRawAccelReady = false;
  bool imuRawGyroReady = false;
  bool imuRawMagReady = false;
  bool imuFilterReady = false;
  bool imuCalibrationStored = false;
  bool imuAccelCalibrated = false;
  bool imuGyroCalibrated = false;
  bool imuMagCalibrated = false;
  bool imuVerticalCalibrated = false;
  bool imuAccelWizardActive = false;
  uint8_t imuAccelPoseIndex = 0;
  char imuCalibrationMode[16] = "idle";
  char imuCalibrationStatus[96] = "Boot";
  char imuAccelPoseName[24] = "--";
  bool shadowControlReady = false;
  int shadowPidOutput = 0;
  char shadowDirection[16] = "zero";
  bool balanceControlEnabled = false;
  double pidTargetSetpoint = 0.0;
  bool controlSettingsSaved = true;
  char controlSettingsMessage[48] = "loaded";
  float statePositionCounts = 0.0f;
  float statePosition = 0.0f;
  float stateRawVelocity = 0.0f;
  float stateVelocity = 0.0f;
  float stateAngleError = 0.0f;
  float stateAngularVelocity = 0.0f;
  float stateRawAngularAcceleration = 0.0f;
  float stateAngularAcceleration = 0.0f;
  double statePositionTerm = 0.0;
  double stateVelocityTerm = 0.0;
  double stateAngleTerm = 0.0;
  double stateAngularVelocityTerm = 0.0;
  double stateAngularAccelerationTerm = 0.0;
  double stateOutputBeforeLimit = 0.0;
  bool stateOutputSaturated = false;
  double stateSaturationCorrection = 0.0;
  double stateGainPosition = 0.0;
  double stateGainVelocity = 0.0;
  double stateGainAngle = 0.0;
  double stateGainAngularVelocity = 0.0;
  double stateGainAngularAcceleration = 0.0;
  float stateVelocityFilterBeta = 0.0f;
  float stateAngularAccelerationFilterBeta = 0.0f;
  bool stateCalibrationWizardActive = false;
  uint8_t stateCalibrationStage = 0;
  bool benchTestArmed = false;
  bool benchTestActive = false;
  unsigned long benchArmRemainingMs = 0;
  unsigned long benchWatchdogAgeMs = 0;
  char benchTestCommand[24] = "stopped";
  float angleAccelDeg = 0.0f;
  float angleFilteredDeg = 0.0f;
  float angleComplementaryDeg = 0.0f;
  float angleKalmanDeg = 0.0f;
  float selectedAngleDeg = 0.0f;
  float gyroRateDegPerSec = 0.0f;
  float turnRateDegPerSec = 0.0f;
  char turnDirection[12] = "quieto";

  long rawLeftEncoder = 0;
  long rawRightEncoder = 0;
  long correctedLeftEncoder = 0;
  long correctedRightEncoder = 0;
  float leftDistanceMm = 0.0f;
  float rightDistanceMm = 0.0f;
  float leftSpeed = 0.0f;
  float rightSpeed = 0.0f;
  float speedAverage = 0.0f;
  float speedDifference = 0.0f;
  float leftSpeedMmPerSec = 0.0f;
  float rightSpeedMmPerSec = 0.0f;
  float speedAverageMmPerSec = 0.0f;
  float speedDifferenceMmPerSec = 0.0f;
  float encoderSyncError = 0.0f;
  int encoderSyncCorrection = 0;
  bool encoderSyncEnabled = false;
  double encoderSyncKp = 0.0;
  float encoderSyncDeadband = 0.0f;
  int encoderSyncMaxCorrection = 0;
  float encoderSyncTargetDifference = 0.0f;
  bool gyroZHoldEnabled = false;
  double gyroZHoldKp = 0.0;
  float gyroZHoldDeadband = 0.0f;
  int gyroZHoldMaxCorrection = 0;
  int gyroZHoldCorrection = 0;
  bool speedHoldEnabled = false;
  double speedHoldKp = 0.0;
  float speedHoldDeadband = 0.0f;
  double speedHoldMaxAngleDeg = 0.0;
  double speedHoldAngleCorrectionDeg = 0.0;
  float driveForward = 0.0f;
  float driveTurn = 0.0f;
  float driveAngleOffsetDeg = 0.0f;
  int driveTurnPwm = 0;
  bool driveCommandActive = false;
  bool autoRecoveryEnabled = false;
  bool autoRecoveryWaiting = false;
  bool autoRecoveryCalibrating = false;
  unsigned long autoRecoveryStableMs = 0;
  char autoRecoveryState[20] = "Boot";
  bool autoTrimEnabled = false;
  bool autoTrimDone = false;
  double autoTrimOffsetDeg = 0.0;
  double autoTrimScore = 0.0;
  double autoTrimBestScore = 0.0;
  uint8_t autoTrimNoImprovementCycles = 0;
  unsigned long autoTrimStableElapsedMs = 0;
  char autoTrimPhase[20] = "Idle";
  char autoTrimDirection[8] = "none";
  char autoTrimBlockReason[40] = "disabled";
  char autoTrimStopReason[40] = "";

  int leftPwm = 0;
  int rightPwm = 0;
  int balancePwm = 0;

  double pidSetpoint = 0.0;
  double pidInput = 0.0;
  double pidError = 0.0;
  double pidOutput = 0.0;
  double pidPTerm = 0.0;
  double pidITerm = 0.0;
  double pidDTerm = 0.0;
  double pidOutputBeforeLimit = 0.0;
  double pidOutputAfterLimit = 0.0;
  double pidKp = 0.0;
  double pidKi = 0.0;
  double pidKd = 0.0;
  float pidIntegral = 0.0f;
  double pidIntegralLimit = 0.0;
  double pidITermLimit = 0.0;
  bool pidIntegralEnabled = true;
  int pidOutputMin = 0;
  int pidOutputMax = 0;
  int motorLeftMinPwm = 0;
  int motorLeftMaxPwm = 0;
  int motorRightMinPwm = 0;
  int motorRightMaxPwm = 0;
  double motorLeftCompensation = 1.0;
  double motorRightCompensation = 1.0;
  uint32_t controlPeriodMs = 0;

  bool imuReady = false;
  bool gyroCalibrated = false;
  bool angleInitialized = false;
  bool motorsEnabled = false;
  bool safetyStop = true;
  bool safetyFault = true;
  bool otaAvailable = false;
  bool otaUpdating = false;
  char faultMessage[80] = "Boot";
};

struct RobotCommand {
  bool enableMotors = false;
  bool disableMotors = false;
  bool stopMotors = false;
  bool resetEncoders = false;
  bool calibrateGyro = false;
  bool calibrateVertical = false;
  bool startAccelCalibration = false;
  bool captureAccelPose = false;
  bool calibrateMagnetometer = false;
  bool clearImuCalibration = false;
  bool armBenchTest = false;
  bool disarmBenchTest = false;
  bool updateBenchTest = false;
  bool otaStart = false;
  bool otaEnd = false;
  bool testLeftMotor = false;
  bool testRightMotor = false;
  bool testBothMotors = false;
  bool updatePidTunings = false;
  bool updatePidSetpoint = false;
  bool updatePidMaxPwm = false;
  bool updateMotorPwmLimits = false;
  bool updateStateFeedback = false;
  bool startStateCalibrationWizard = false;
  bool updateStateCalibrationStage = false;
  bool restoreStateCalibrationSnapshot = false;
  bool finishStateCalibrationWizard = false;
  bool updateIntegralLimit = false;
  bool updateITermLimit = false;
  bool updateIntegralEnabled = false;
  bool resetIntegral = false;
  bool updateEncoderSyncEnabled = false;
  bool updateEncoderSyncConfig = false;
  bool updateEncoderSyncTarget = false;
  bool updateGyroZHoldEnabled = false;
  bool updateGyroZHoldConfig = false;
  bool updateSpeedHoldEnabled = false;
  bool updateSpeedHoldConfig = false;
  bool updateDriveCommand = false;
  bool updateAutoTrimEnabled = false;
  bool resetAutoTrim = false;
  double pidKp = 0.0;
  double pidKi = 0.0;
  double pidKd = 0.0;
  double pidSetpoint = 0.0;
  double pidIntegralLimit = 0.0;
  double pidITermLimit = 0.0;
  bool pidIntegralEnabled = true;
  bool encoderSyncEnabled = false;
  double encoderSyncKp = 0.0;
  float encoderSyncDeadband = 0.0f;
  int encoderSyncMaxCorrection = 0;
  float encoderSyncTargetDifference = 0.0f;
  bool gyroZHoldEnabled = false;
  double gyroZHoldKp = 0.0;
  int gyroZHoldMaxCorrection = 0;
  bool speedHoldEnabled = false;
  double speedHoldKp = 0.0;
  double speedHoldMaxAngleDeg = 0.0;
  float driveForward = 0.0f;
  float driveTurn = 0.0f;
  bool autoTrimEnabled = false;
  int pidMaxPwm = 0;
  int motorLeftMinPwm = 0;
  int motorLeftMaxPwm = 0;
  int motorRightMinPwm = 0;
  int motorRightMaxPwm = 0;
  double motorLeftCompensation = 1.0;
  double motorRightCompensation = 1.0;
  double stateGainPosition = 0.0;
  double stateGainVelocity = 0.0;
  double stateGainAngle = 0.0;
  double stateGainAngularVelocity = 0.0;
  double stateGainAngularAcceleration = 0.0;
  float stateVelocityFilterBeta = 0.0f;
  float stateAngularAccelerationFilterBeta = 0.0f;
  uint8_t stateCalibrationStage = 0;
  int benchLeftPwm = 0;
  int benchRightPwm = 0;
};

namespace SharedState {

void begin();

RobotState getState();
void setState(const RobotState &state);
RobotCommand consumeCommand();

void requestEnableMotors();
void requestDisableMotors();
void requestStop();
void requestEncoderReset();
void requestGyroCalibration();
void requestVerticalCalibration();
void requestAccelCalibrationStart();
void requestAccelPoseCapture();
void requestMagnetometerCalibration();
void requestImuCalibrationClear();
void requestBenchTestArm();
void requestBenchTestDisarm();
void requestBenchTestPwm(int leftPwm, int rightPwm);
void requestOtaStart();
void requestOtaEnd();
void setOtaAvailable(bool available);
void setOtaUpdating(bool updating);
bool isOtaUpdating();
void requestLeftMotorTest();
void requestRightMotorTest();
void requestBothMotorsTest();
void requestPidTunings(double kp, double ki, double kd);
void requestPidSetpoint(double setpoint);
void requestPidMaxPwm(int maxPwm);
void requestMotorPwmLimits(int leftMinPwm, int leftMaxPwm, int rightMinPwm, int rightMaxPwm,
                           double leftCompensation, double rightCompensation);
void requestStateFeedbackConfig(double positionGain, double velocityGain, double angleGain,
                                double angularVelocityGain, double angularAccelerationGain,
                                float velocityFilterBeta,
                                float angularAccelerationFilterBeta);
void requestStateCalibrationWizardStart();
void requestStateCalibrationStage(uint8_t stage);
void requestStateCalibrationRestore();
void requestStateCalibrationFinish();
void requestIntegralLimit(double limit);
void requestITermLimit(double limit);
void requestIntegralEnabled(bool enabled);
void requestIntegralReset();
void requestEncoderSyncEnabled(bool enabled);
void requestEncoderSyncConfig(double kp, float deadband, int maxCorrection);
void requestEncoderSyncTarget(float targetDifference);
void requestGyroZHoldEnabled(bool enabled);
void requestGyroZHoldConfig(double kp, int maxCorrection);
void requestSpeedHoldEnabled(bool enabled);
void requestSpeedHoldConfig(double kp, double maxAngleDeg);
void requestDriveCommand(float forward, float turn);
void requestAutoTrimEnabled(bool enabled);
void requestAutoTrimReset();

}  // namespace SharedState
