#!/usr/bin/env python3
"""Merge Bayesian PID tuning CSV files and create a per-trial summary.

This script is offline-only: it does not connect to the ESP32 and never sends
motor commands. It reads files generated by pid_tuner_gui.py.

Install dependencies with:
    pip install pandas
"""

from __future__ import annotations

import argparse
import statistics
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd


DEFAULT_INPUT_DIR = Path("tools/pid_logs")
DEFAULT_OUTPUT_DIR = Path("tools/pid_logs")
DEFAULT_PATTERN = "pid_bayesian_test_*.csv"


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Merge Bayesian PID tuning CSV logs")
    parser.add_argument("--input", default=str(DEFAULT_INPUT_DIR), help="Directory with Bayesian test CSV files")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT_DIR), help="Directory for merged output CSV files")
    parser.add_argument("--pattern", default=DEFAULT_PATTERN, help="Glob pattern for input CSV files")
    parser.add_argument("--safe-angle-limit", type=float, default=25.0, help="Instability threshold in degrees")
    parser.add_argument("--merged-name", default="", help="Optional output filename for merged samples")
    parser.add_argument("--summary-name", default="", help="Optional output filename for per-trial summary")
    return parser


def safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def safe_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    text = str(value).strip().lower()
    return text in {"1", "true", "yes", "y", "on"}


def find_input_files(input_dir: Path, pattern: str) -> list[Path]:
    return sorted(path for path in input_dir.glob(pattern) if path.is_file())


def read_trial_csv(path: Path, trial_index: int) -> pd.DataFrame:
    frame = pd.read_csv(path)
    frame["source_file"] = path.name
    frame["source_path"] = str(path)
    frame["trial_index"] = trial_index
    if "timestamp" in frame.columns and not frame.empty:
        frame["trial_start_timestamp"] = frame["timestamp"].iloc[0]
    else:
        frame["trial_start_timestamp"] = ""
    return frame


def compute_trial_summary(frame: pd.DataFrame, safe_angle_limit: float) -> dict[str, Any]:
    if frame.empty:
        return {
            "trial_index": None,
            "source_file": "",
            "kp": 0.0,
            "ki": 0.0,
            "kd": 0.0,
            "setpoint": 0.0,
            "maxPwm": 0,
            "samples": 0,
            "mean_abs_error": 999.0,
            "max_abs_error": 999.0,
            "angle_stddev": 999.0,
            "saturation_percent": 100.0,
            "safetyStop": True,
            "faultMessage": "empty file",
            "score": 12000.0,
        }

    setpoint = safe_float(frame.get("setpoint", pd.Series([0.0])).iloc[0])
    max_pwm = max(1, int(safe_float(frame.get("maxPwm", pd.Series([1])).iloc[0], 1.0)))
    if "error" in frame.columns:
        errors = [abs(safe_float(value)) for value in frame["error"]]
    else:
        errors = [abs(setpoint - safe_float(value)) for value in frame.get("angle", pd.Series(dtype=float))]
    angles = [safe_float(value) for value in frame.get("angle", pd.Series(dtype=float))]
    outputs = [abs(safe_float(value)) for value in frame.get("pidOutput", pd.Series(dtype=float))]
    safety_stop = any(safe_bool(value) for value in frame.get("safetyStop", pd.Series(dtype=bool)))
    saturated = sum(1 for output in outputs if output >= 0.95 * max_pwm)
    sample_count = len(frame)

    mean_abs_error = statistics.fmean(errors) if errors else 999.0
    max_abs_error = max(errors) if errors else 999.0
    angle_stddev = statistics.pstdev(angles) if len(angles) > 1 else 0.0
    saturation_percent = 100.0 * saturated / sample_count if sample_count else 100.0
    safety_penalty = 10000.0 if safety_stop else 0.0
    instability_penalty = 1000.0 if max_abs_error > safe_angle_limit else 0.0
    score = (
        mean_abs_error
        + 0.6 * angle_stddev
        + 0.2 * max_abs_error
        + 0.05 * saturation_percent
        + safety_penalty
        + instability_penalty
    )
    fault_messages = [str(value) for value in frame.get("faultMessage", pd.Series(dtype=str)) if str(value)]

    return {
        "trial_index": int(frame["trial_index"].iloc[0]),
        "source_file": str(frame["source_file"].iloc[0]),
        "trial_start_timestamp": frame["trial_start_timestamp"].iloc[0],
        "kp": safe_float(frame.get("kp", pd.Series([0.0])).iloc[0]),
        "ki": safe_float(frame.get("ki", pd.Series([0.0])).iloc[0]),
        "kd": safe_float(frame.get("kd", pd.Series([0.0])).iloc[0]),
        "setpoint": setpoint,
        "maxPwm": max_pwm,
        "samples": sample_count,
        "mean_abs_error": mean_abs_error,
        "max_abs_error": max_abs_error,
        "angle_stddev": angle_stddev,
        "saturation_percent": saturation_percent,
        "safetyStop": safety_stop,
        "faultMessage": fault_messages[-1] if fault_messages else "",
        "score": score,
    }


def main() -> int:
    args = build_arg_parser().parse_args()
    input_dir = Path(args.input)
    output_dir = Path(args.output)
    files = find_input_files(input_dir, args.pattern)
    if not files:
        print(f"No files found in {input_dir} matching {args.pattern}")
        return 1

    output_dir.mkdir(parents=True, exist_ok=True)
    frames = []
    summary_rows = []
    for index, path in enumerate(files, start=1):
        frame = read_trial_csv(path, index)
        frames.append(frame)
        summary_rows.append(compute_trial_summary(frame, args.safe_angle_limit))

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    merged_name = args.merged_name or f"bayesian_merged_samples_{timestamp}.csv"
    summary_name = args.summary_name or f"bayesian_merged_summary_{timestamp}.csv"
    merged_path = output_dir / merged_name
    summary_path = output_dir / summary_name

    merged = pd.concat(frames, ignore_index=True)
    summary = pd.DataFrame(summary_rows).sort_values("score", ascending=True)
    merged.to_csv(merged_path, index=False)
    summary.to_csv(summary_path, index=False)

    best = summary.iloc[0]
    print(f"Merged {len(files)} Bayesian CSV files")
    print(f"Samples CSV: {merged_path}")
    print(f"Summary CSV: {summary_path}")
    print(
        "Best trial: "
        f"trial={int(best['trial_index'])} "
        f"score={safe_float(best['score']):.3f} "
        f"Kp={safe_float(best['kp']):.3f} "
        f"Ki={safe_float(best['ki']):.3f} "
        f"Kd={safe_float(best['kd']):.3f} "
        f"source={best['source_file']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
